export interface Message {
  id: string; // Unique message ID (can be generated by backend or Firestore)
  senderId: string;
  receiverId: string;
  content: string;
  timestamp: string; // Use string for easy serialization
}
